---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kingest.fullname" . }}
  labels:
    {{- include "kingest.labels" . | nindent 4 }}
rules:
  - apiGroups: ["apps", ""]
    resources: ["pods", "services", "replicationcontrollers", "deployments"]
    verbs: ["get", "watch", "list"]
