{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kingest.serviceAccountName" . }}
  labels:
    {{- include "kingest.labels" . | nindent 4 }}
{{- end -}}
