{{- if not .Values.externalConfig.secretRef.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vcs-connect.fullname" . }}
stringData:
  {{- with .Values.config.github }}
  GITHUB_BASE_URL: {{ .baseURL | quote }}
  GITHUB_UPLOAD_URL: {{ .uploadURL | quote }}
  GITHUB_USERNAME: {{ .username | quote }}
  GITHUB_ACCESS_TOKEN: {{ .accessToken | quote }}
  GITHUB_ORGANIZATIONS: {{ join "," .organizations | quote }}
  {{- end }}
  {{- with .Values.config.gitlab }}
  GITLAB_BASE_URL: {{ .baseURL | quote }}
  GITLAB_USERNAME:  {{ .username | quote }}
  GITLAB_ACCESS_TOKEN: {{ .accessToken | quote }}
  GITLAB_GROUPS: {{ join "," .groups | quote }}
  {{- end }}
{{- end }}